version: '3.9'
services:
  apachetxt:
    image: httpd
    ports:
      - 8080:80
    volumes:
      - apachetxt:/usr/local/apache2/htdocs
    networks:
      - rede

networks:
    rede:
      driver: bridge